name: Snowsplash
version: '1.0-SNAPSHOT'
main: com.liphium.snowsplash.Snowsplash
api-version: '1.21'
depend:
  - Multiverse-Core

commands:
  set:
    description: "Set a location."
  timer:
    description: "Configure the timer."
